server:
  port: 8080

spring:
  application:
    name: sales-application
  datasource:
    url: jdbc:h2:mem:salesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG